// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Models
{
    public partial class TollFreeDates
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
    }
}