// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Models
{
    public partial class TollFreeVehicles
    {
        public int Id { get; set; }
        public string VehicleType { get; set; }
    }
}